// figma node: 155:139 Ajustes — iPhone 14
export function AjustesIPhone14(_p = {}) {
  const props = _p;
  return (
    <div className={props.className} style={{
      width: 390,
      height: 1876,
      overflow: "hidden",
      backgroundColor: "rgb(250,250,248)",
      position: "relative",
      color: "rgba(3,9,16,0.57)",
      ...props.style,
    }}>
      <svg width={393} height={50} viewBox="0 0 393 50" fill="none" style={{
        position: "absolute",
        left: 0,
        top: 0,
        width: 393,
        height: 50,
        overflow: "hidden",
        color: "rgb(245,200,66)",
      }}>
        <path d={"M 0 0 L 393 0 L 393 50 L 0 50 L 0 0 Z"} fill="currentColor" fillRule="nonzero" />
      </svg>
      <div style={{
        position: "absolute",
        left: 0,
        top: 50,
        width: 396,
        height: 130,
        overflow: "hidden",
        backgroundColor: "rgb(245,200,66)",
      }}>
        <span style={{
          position: "absolute",
          left: 22,
          top: 20,
          width: 22,
          height: 19,
          fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 16,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(3,29,68)",
        }}>􀈖</span>
        <span style={{
          position: "absolute",
          left: 42,
          top: 22,
          width: 33,
          height: 16,
          opacity: 0.6,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 500,
          fontSize: 13,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(3,29,68)",
        }}>Perfil</span>
        <div style={{
          position: "absolute",
          left: 20,
          top: 52,
          width: 64,
          height: 64,
          overflow: "hidden",
          borderRadius: 32,
          backgroundColor: "rgb(3,29,68)",
        }}>
          <span style={{
            position: "absolute",
            left: 22,
            top: 16,
            width: 20,
            height: 31,
            fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
            fontWeight: 700,
            fontSize: 26,
            whiteSpace: "nowrap",
            lineHeight: "100%",
            color: "rgb(255,255,255)",
          }}>A</span>
        </div>
        <span style={{
          position: "absolute",
          left: 96,
          top: 54,
          width: 119,
          height: 21,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 700,
          fontSize: 17,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(3,29,68)",
        }}>Adri Carretero</span>
        <span style={{
          position: "absolute",
          left: 96,
          top: 75,
          width: 89,
          height: 15,
          opacity: 0.55,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 12,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(3,29,68)",
        }}>adri@sabor.app</span>
        <div style={{
          position: "absolute",
          left: 96,
          top: 97,
          width: 112,
          height: 22,
          overflow: "hidden",
          borderRadius: 11,
          backgroundColor: "rgba(112,162,136,0.15)",
        }}>
          <span style={{
            position: "absolute",
            left: 8,
            top: 5,
            width: 15,
            height: 12,
            fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
            fontWeight: 400,
            fontSize: 10,
            whiteSpace: "nowrap",
            lineHeight: "100%",
            color: "rgb(93,146,118)",
          }}>􀈧</span>
          <span style={{
            position: "absolute",
            left: 22,
            top: 5,
            width: 57,
            height: 12,
            fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
            fontWeight: 600,
            fontSize: 10,
            whiteSpace: "nowrap",
            lineHeight: "100%",
            color: "rgb(93,146,118)",
          }}>Editar perfil</span>
        </div>
      </div>
      <span style={{
        position: "absolute",
        left: 253,
        top: 136,
        width: 98,
        height: 31,
        fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
        fontWeight: 700,
        fontSize: 26,
        whiteSpace: "nowrap",
        lineHeight: "100%",
        color: "rgb(3,29,68)",
      }}>Ajustes</span>
      <span style={{
        position: "absolute",
        left: 20,
        top: 190,
        width: 48,
        height: 12,
        fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
        fontWeight: 700,
        fontSize: 10,
        whiteSpace: "nowrap",
        lineHeight: "100%",
        letterSpacing: "1.200px",
        color: "rgb(107,114,128)",
      }}>CUENTA</span>
      <div style={{
        position: "absolute",
        left: 16,
        top: 212,
        width: 343,
        height: 208,
        overflow: "hidden",
        borderRadius: 18,
        backgroundColor: "rgb(255,255,255)",
        boxShadow: "inset 0 0 0 1px rgb(217,222,227)",
      }}>
        <div style={{
          position: "absolute",
          left: 12,
          top: 8,
          width: 36,
          height: 36,
          overflow: "hidden",
          borderRadius: 10,
          backgroundColor: "rgba(237,237,255,0)",
        }}>
          <span style={{
            position: "absolute",
            left: 6,
            top: 8,
            width: 24,
            height: 20,
            fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
            fontWeight: 400,
            fontSize: 17,
            whiteSpace: "nowrap",
            lineHeight: "100%",
            color: "rgb(3,29,68)",
          }}>􀈶</span>
        </div>
        <span style={{
          position: "absolute",
          left: 58,
          top: 10,
          width: 130,
          height: 17,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 600,
          fontSize: 14,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(31,41,55)",
        }}>Nombre y apellidos</span>
        <span style={{
          position: "absolute",
          left: 58,
          top: 28,
          width: 74,
          height: 13,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 11,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(107,114,128)",
        }}>Adri Carretero</span>
        <span style={{
          position: "absolute",
          left: 320,
          top: 19,
          width: 15,
          height: 14,
          fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 12,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(217,222,227)",
        }}>􀈗</span>
        <div style={{
          position: "absolute",
          left: 52,
          top: 52,
          width: 279,
          height: 1,
          backgroundColor: "rgb(242,244,245)",
        }} />
        <div style={{
          position: "absolute",
          left: 12,
          top: 60,
          width: 36,
          height: 36,
          overflow: "hidden",
          borderRadius: 10,
          backgroundColor: "rgba(224,247,232,0)",
        }}>
          <span style={{
            position: "absolute",
            left: 6,
            top: 8,
            width: 24,
            height: 20,
            fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
            fontWeight: 400,
            fontSize: 17,
            whiteSpace: "nowrap",
            lineHeight: "100%",
            color: "rgb(3,29,68)",
          }}>􀈣</span>
        </div>
        <span style={{
          position: "absolute",
          left: 58,
          top: 62,
          width: 37,
          height: 17,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 600,
          fontSize: 14,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(31,41,55)",
        }}>Email</span>
        <span style={{
          position: "absolute",
          left: 58,
          top: 80,
          width: 82,
          height: 13,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 11,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(107,114,128)",
        }}>adri@sabor.app</span>
        <span style={{
          position: "absolute",
          left: 320,
          top: 71,
          width: 15,
          height: 14,
          fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 12,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(217,222,227)",
        }}>􀈗</span>
        <div style={{
          position: "absolute",
          left: 52,
          top: 104,
          width: 279,
          height: 1,
          backgroundColor: "rgb(242,244,245)",
        }} />
        <div style={{
          position: "absolute",
          left: 12,
          top: 112,
          width: 36,
          height: 36,
          overflow: "hidden",
          borderRadius: 10,
          backgroundColor: "rgba(255,247,237,0)",
        }}>
          <span style={{
            position: "absolute",
            left: 6,
            top: 8,
            width: 23,
            height: 20,
            fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
            fontWeight: 400,
            fontSize: 17,
            whiteSpace: "nowrap",
            lineHeight: "100%",
            color: "rgb(3,29,68)",
          }}>􀍆</span>
        </div>
        <span style={{
          position: "absolute",
          left: 58,
          top: 114,
          width: 59,
          height: 17,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 600,
          fontSize: 14,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(31,41,55)",
        }}>Teléfono</span>
        <span style={{
          position: "absolute",
          left: 58,
          top: 132,
          width: 87,
          height: 13,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 11,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(107,114,128)",
        }}>+34 6•• ••• •••</span>
        <span style={{
          position: "absolute",
          left: 320,
          top: 123,
          width: 15,
          height: 14,
          fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 12,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(217,222,227)",
        }}>􀈗</span>
        <div style={{
          position: "absolute",
          left: 52,
          top: 156,
          width: 279,
          height: 1,
          backgroundColor: "rgb(242,244,245)",
        }} />
        <div style={{
          position: "absolute",
          left: 12,
          top: 164,
          width: 36,
          height: 36,
          overflow: "hidden",
          borderRadius: 10,
          backgroundColor: "rgba(245,237,255,0)",
        }}>
          <span style={{
            position: "absolute",
            left: 7,
            top: 8,
            width: 22,
            height: 20,
            fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
            fontWeight: 400,
            fontSize: 17,
            whiteSpace: "nowrap",
            lineHeight: "100%",
            color: "rgb(3,29,68)",
          }}>􀉌</span>
        </div>
        <span style={{
          position: "absolute",
          left: 58,
          top: 166,
          width: 79,
          height: 17,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 600,
          fontSize: 14,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(31,41,55)",
        }}>Contraseña</span>
        <span style={{
          position: "absolute",
          left: 58,
          top: 184,
          width: 134,
          height: 13,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 11,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(107,114,128)",
        }}>Modificada hace 3 meses</span>
        <span style={{
          position: "absolute",
          left: 320,
          top: 175,
          width: 15,
          height: 14,
          fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 12,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(217,222,227)",
        }}>􀈗</span>
      </div>
      <span style={{
        position: "absolute",
        left: 20,
        top: 438,
        width: 55,
        height: 12,
        fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
        fontWeight: 700,
        fontSize: 10,
        whiteSpace: "nowrap",
        lineHeight: "100%",
        letterSpacing: "1.200px",
        color: "rgb(107,114,128)",
      }}>ENTREGA</span>
      <div style={{
        position: "absolute",
        left: 16,
        top: 460,
        width: 343,
        height: 156,
        overflow: "hidden",
        borderRadius: 18,
        backgroundColor: "rgb(255,255,255)",
        boxShadow: "inset 0 0 0 1px rgb(217,222,227)",
      }}>
        <div style={{
          position: "absolute",
          left: 12,
          top: 8,
          width: 36,
          height: 36,
          overflow: "hidden",
          borderRadius: 10,
          backgroundColor: "rgba(224,247,232,0)",
        }}>
          <span style={{
            position: "absolute",
            left: 9,
            top: 8,
            width: 19,
            height: 20,
            fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
            fontWeight: 400,
            fontSize: 17,
            whiteSpace: "nowrap",
            lineHeight: "100%",
            color: "rgb(3,29,68)",
          }}>􀉀</span>
        </div>
        <span style={{
          position: "absolute",
          left: 58,
          top: 10,
          width: 121,
          height: 17,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 600,
          fontSize: 14,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(31,41,55)",
        }}>Dirección de casa</span>
        <span style={{
          position: "absolute",
          left: 58,
          top: 28,
          width: 125,
          height: 13,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 11,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(107,114,128)",
        }}>C/ Exemple 12, Sabadell</span>
        <span style={{
          position: "absolute",
          left: 320,
          top: 19,
          width: 15,
          height: 14,
          fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 12,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(217,222,227)",
        }}>􀈗</span>
        <div style={{
          position: "absolute",
          left: 52,
          top: 52,
          width: 279,
          height: 1,
          backgroundColor: "rgb(242,244,245)",
        }} />
        <span style={{
          position: "absolute",
          left: 58,
          top: 62,
          width: 140,
          height: 17,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 600,
          fontSize: 14,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(31,41,55)",
        }}>Dirección del trabajo</span>
        <span style={{
          position: "absolute",
          left: 58,
          top: 80,
          width: 52,
          height: 13,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 11,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(107,114,128)",
        }}>Sin añadir</span>
        <div style={{
          position: "absolute",
          left: 267,
          top: 68,
          width: 64,
          height: 20,
          overflow: "hidden",
          borderRadius: 10,
          backgroundColor: "rgba(218,183,133,0.15)",
        }}>
          <span style={{
            position: "absolute",
            left: 8,
            top: 4,
            width: 42,
            height: 12,
            fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
            fontWeight: 700,
            fontSize: 10,
            whiteSpace: "nowrap",
            lineHeight: "100%",
            color: "rgb(138,107,41)",
          }}>+ Añadir</span>
        </div>
        <div style={{
          position: "absolute",
          left: 52,
          top: 104,
          width: 279,
          height: 1,
          backgroundColor: "rgb(242,244,245)",
        }} />
        <div style={{
          position: "absolute",
          left: 12,
          top: 112,
          width: 36,
          height: 36,
          overflow: "hidden",
          borderRadius: 10,
          backgroundColor: "rgba(255,247,237,0)",
        }}>
          <span style={{
            position: "absolute",
            left: 8,
            top: 8,
            width: 20,
            height: 20,
            fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
            fontWeight: 400,
            fontSize: 17,
            whiteSpace: "nowrap",
            lineHeight: "100%",
            color: "rgb(3,29,68)",
          }}>􀊀</span>
        </div>
        <span style={{
          position: "absolute",
          left: 58,
          top: 114,
          width: 169,
          height: 17,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 600,
          fontSize: 14,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(31,41,55)",
        }}>Instrucciones de entrega</span>
        <span style={{
          position: "absolute",
          left: 58,
          top: 132,
          width: 93,
          height: 13,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 11,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(107,114,128)",
        }}>Dejar en la puerta</span>
        <span style={{
          position: "absolute",
          left: 320,
          top: 123,
          width: 15,
          height: 14,
          fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 12,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(217,222,227)",
        }}>􀈗</span>
      </div>
      <span style={{
        position: "absolute",
        left: 20,
        top: 634,
        width: 32,
        height: 12,
        fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
        fontWeight: 700,
        fontSize: 10,
        whiteSpace: "nowrap",
        lineHeight: "100%",
        letterSpacing: "1.200px",
        color: "rgb(107,114,128)",
      }}>PAGO</span>
      <div style={{
        position: "absolute",
        left: 16,
        top: 656,
        width: 343,
        height: 156,
        overflow: "hidden",
        borderRadius: 18,
        backgroundColor: "rgb(255,255,255)",
        boxShadow: "inset 0 0 0 1px rgb(217,222,227)",
      }}>
        <div style={{
          position: "absolute",
          left: 12,
          top: 8,
          width: 36,
          height: 36,
          overflow: "hidden",
          borderRadius: 10,
          backgroundColor: "rgba(237,237,255,0)",
        }}>
          <span style={{
            position: "absolute",
            left: 4,
            top: 8,
            width: 29,
            height: 20,
            fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
            fontWeight: 400,
            fontSize: 17,
            whiteSpace: "nowrap",
            lineHeight: "100%",
            color: "rgb(3,29,68)",
          }}>􀊑</span>
        </div>
        <span style={{
          position: "absolute",
          left: 58,
          top: 10,
          width: 110,
          height: 17,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 600,
          fontSize: 14,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(31,41,55)",
        }}>Tarjeta principal</span>
        <span style={{
          position: "absolute",
          left: 58,
          top: 28,
          width: 79,
          height: 13,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 11,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(107,114,128)",
        }}>Visa •••• 4821</span>
        <div style={{
          position: "absolute",
          left: 279,
          top: 16,
          width: 52,
          height: 20,
          overflow: "hidden",
          borderRadius: 10,
          backgroundColor: "rgba(112,162,136,0.15)",
        }}>
          <span style={{
            position: "absolute",
            left: 8,
            top: 4,
            width: 32,
            height: 12,
            fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
            fontWeight: 700,
            fontSize: 10,
            whiteSpace: "nowrap",
            lineHeight: "100%",
            color: "rgb(93,146,118)",
          }}>Activa</span>
        </div>
        <div style={{
          position: "absolute",
          left: 52,
          top: 52,
          width: 279,
          height: 1,
          backgroundColor: "rgb(242,244,245)",
        }} />
        <div style={{
          position: "absolute",
          left: 12,
          top: 60,
          width: 36,
          height: 36,
          overflow: "hidden",
          borderRadius: 10,
          backgroundColor: "rgb(224,247,232)",
        }}>
          <span style={{
            position: "absolute",
            left: 8,
            top: 8,
            width: 21,
            height: 20,
            fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
            fontWeight: 400,
            fontSize: 17,
            whiteSpace: "nowrap",
            lineHeight: "100%",
            color: "rgb(3,29,68)",
          }}>􀊵</span>
        </div>
        <span style={{
          position: "absolute",
          left: 58,
          top: 62,
          width: 42,
          height: 17,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 600,
          fontSize: 14,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(31,41,55)",
        }}>Bizum</span>
        <span style={{
          position: "absolute",
          left: 58,
          top: 80,
          width: 60,
          height: 13,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 11,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(107,114,128)",
        }}>Sin vincular</span>
        <div style={{
          position: "absolute",
          left: 255,
          top: 68,
          width: 76,
          height: 20,
          overflow: "hidden",
          borderRadius: 10,
          backgroundColor: "rgba(218,183,133,0.15)",
        }}>
          <span style={{
            position: "absolute",
            left: 8,
            top: 4,
            width: 51,
            height: 12,
            fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
            fontWeight: 700,
            fontSize: 10,
            whiteSpace: "nowrap",
            lineHeight: "100%",
            color: "rgb(138,107,41)",
          }}>+ Vincular</span>
        </div>
        <div style={{
          position: "absolute",
          left: 52,
          top: 104,
          width: 279,
          height: 1,
          backgroundColor: "rgb(242,244,245)",
        }} />
        <div style={{
          position: "absolute",
          left: 12,
          top: 112,
          width: 36,
          height: 36,
          overflow: "hidden",
          borderRadius: 10,
          backgroundColor: "rgb(245,237,255)",
        }}>
          <span style={{
            position: "absolute",
            left: 9,
            top: 8,
            width: 21,
            height: 20,
            fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
            fontWeight: 400,
            fontSize: 17,
            whiteSpace: "nowrap",
            lineHeight: "100%",
            color: "rgb(3,29,68)",
          }}>􀈠</span>
        </div>
        <span style={{
          position: "absolute",
          left: 58,
          top: 114,
          width: 141,
          height: 17,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 600,
          fontSize: 14,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(31,41,55)",
        }}>Datos de facturación</span>
        <span style={{
          position: "absolute",
          left: 58,
          top: 132,
          width: 69,
          height: 13,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 11,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(107,114,128)",
        }}>Uso personal</span>
        <span style={{
          position: "absolute",
          left: 320,
          top: 123,
          width: 15,
          height: 14,
          fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 12,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(217,222,227)",
        }}>􀈗</span>
      </div>
      <span style={{
        position: "absolute",
        left: 20,
        top: 830,
        width: 102,
        height: 12,
        fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
        fontWeight: 700,
        fontSize: 10,
        whiteSpace: "nowrap",
        lineHeight: "100%",
        letterSpacing: "1.200px",
        color: "rgb(107,114,128)",
      }}>NOTIFICACIONES</span>
      <div style={{
        position: "absolute",
        left: 16,
        top: 852,
        width: 343,
        height: 208,
        overflow: "hidden",
        borderRadius: 18,
        backgroundColor: "rgb(255,255,255)",
        boxShadow: "inset 0 0 0 1px rgb(217,222,227)",
      }}>
        <div style={{
          position: "absolute",
          left: 12,
          top: 8,
          width: 36,
          height: 36,
          overflow: "hidden",
          borderRadius: 10,
          backgroundColor: "rgba(224,247,232,0)",
        }}>
          <span style={{
            position: "absolute",
            left: 9,
            top: 8,
            width: 19,
            height: 20,
            fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
            fontWeight: 400,
            fontSize: 17,
            whiteSpace: "nowrap",
            lineHeight: "100%",
            color: "rgb(3,29,68)",
          }}>􀉨</span>
        </div>
        <span style={{
          position: "absolute",
          left: 58,
          top: 19,
          width: 163,
          height: 17,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 600,
          fontSize: 14,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(31,41,55)",
        }}>Confirmación de pedido</span>
        <div style={{
          position: "absolute",
          left: 295,
          top: 13,
          width: 44,
          height: 26,
          overflow: "hidden",
          borderRadius: 13,
          backgroundColor: "rgb(112,162,136)",
        }}>
          <div style={{
            position: "absolute",
            left: 21,
            top: 3,
            width: 20,
            height: 20,
            borderRadius: 10,
            backgroundColor: "rgb(255,255,255)",
          }} />
        </div>
        <div style={{
          position: "absolute",
          left: 52,
          top: 52,
          width: 279,
          height: 1,
          backgroundColor: "rgb(242,244,245)",
        }} />
        <div style={{
          position: "absolute",
          left: 12,
          top: 60,
          width: 36,
          height: 36,
          overflow: "hidden",
          borderRadius: 10,
          backgroundColor: "rgba(255,247,237,0)",
        }}>
          <span style={{
            position: "absolute",
            left: 9,
            top: 8,
            width: 20,
            height: 20,
            fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
            fontWeight: 400,
            fontSize: 17,
            whiteSpace: "nowrap",
            lineHeight: "100%",
            color: "rgb(3,29,68)",
          }}>􀉎</span>
        </div>
        <span style={{
          position: "absolute",
          left: 58,
          top: 71,
          width: 185,
          height: 17,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 600,
          fontSize: 14,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(31,41,55)",
        }}>Seguimiento en tiempo real</span>
        <div style={{
          position: "absolute",
          left: 295,
          top: 65,
          width: 44,
          height: 26,
          overflow: "hidden",
          borderRadius: 13,
          backgroundColor: "rgb(112,162,136)",
        }}>
          <div style={{
            position: "absolute",
            left: 21,
            top: 3,
            width: 20,
            height: 20,
            borderRadius: 10,
            backgroundColor: "rgb(255,255,255)",
          }} />
        </div>
        <div style={{
          position: "absolute",
          left: 52,
          top: 104,
          width: 279,
          height: 1,
          backgroundColor: "rgb(242,244,245)",
        }} />
        <div style={{
          position: "absolute",
          left: 12,
          top: 112,
          width: 36,
          height: 36,
          overflow: "hidden",
          borderRadius: 10,
          backgroundColor: "rgba(255,237,240,0)",
        }}>
          <span style={{
            position: "absolute",
            left: 9,
            top: 8,
            width: 22,
            height: 20,
            fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
            fontWeight: 400,
            fontSize: 17,
            whiteSpace: "nowrap",
            lineHeight: "100%",
            color: "rgb(3,29,68)",
          }}>􀋈</span>
        </div>
        <span style={{
          position: "absolute",
          left: 58,
          top: 123,
          width: 155,
          height: 17,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 600,
          fontSize: 14,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(31,41,55)",
        }}>Ofertas y promociones</span>
        <div style={{
          position: "absolute",
          left: 295,
          top: 117,
          width: 44,
          height: 26,
          overflow: "hidden",
          borderRadius: 13,
          backgroundColor: "rgb(217,222,227)",
        }}>
          <div style={{
            position: "absolute",
            left: 3,
            top: 3,
            width: 20,
            height: 20,
            borderRadius: 10,
            backgroundColor: "rgb(255,255,255)",
          }} />
        </div>
        <div style={{
          position: "absolute",
          left: 52,
          top: 156,
          width: 279,
          height: 1,
          backgroundColor: "rgb(242,244,245)",
        }} />
        <div style={{
          position: "absolute",
          left: 12,
          top: 164,
          width: 36,
          height: 36,
          overflow: "hidden",
          borderRadius: 10,
          backgroundColor: "rgba(245,237,255,0)",
        }}>
          <span style={{
            position: "absolute",
            left: 9,
            top: 8,
            width: 21,
            height: 20,
            fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
            fontWeight: 400,
            fontSize: 17,
            whiteSpace: "nowrap",
            lineHeight: "100%",
            color: "rgb(3,29,68)",
          }}>􀉊</span>
        </div>
        <span style={{
          position: "absolute",
          left: 58,
          top: 175,
          width: 173,
          height: 17,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 600,
          fontSize: 14,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(31,41,55)",
        }}>Novedades de guardados</span>
        <div style={{
          position: "absolute",
          left: 295,
          top: 169,
          width: 44,
          height: 26,
          overflow: "hidden",
          borderRadius: 13,
          backgroundColor: "rgb(112,162,136)",
        }}>
          <div style={{
            position: "absolute",
            left: 21,
            top: 3,
            width: 20,
            height: 20,
            borderRadius: 10,
            backgroundColor: "rgb(255,255,255)",
          }} />
        </div>
      </div>
      <span style={{
        position: "absolute",
        left: 20,
        top: 1078,
        width: 89,
        height: 12,
        fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
        fontWeight: 700,
        fontSize: 10,
        whiteSpace: "nowrap",
        lineHeight: "100%",
        letterSpacing: "1.200px",
        color: "rgb(107,114,128)",
      }}>PREFERENCIAS</span>
      <div style={{
        position: "absolute",
        left: 16,
        top: 1100,
        width: 343,
        height: 156,
        overflow: "hidden",
        borderRadius: 18,
        backgroundColor: "rgb(255,255,255)",
        boxShadow: "inset 0 0 0 1px rgb(217,222,227)",
      }}>
        <div style={{
          position: "absolute",
          left: 12,
          top: 8,
          width: 36,
          height: 36,
          overflow: "hidden",
          borderRadius: 10,
          backgroundColor: "rgba(224,247,232,0)",
        }}>
          <span style={{
            position: "absolute",
            left: 9,
            top: 8,
            width: 15,
            height: 20,
            fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
            fontWeight: 400,
            fontSize: 17,
            whiteSpace: "nowrap",
            lineHeight: "100%",
            color: "rgb(3,29,68)",
          }}>􀋘</span>
        </div>
        <span style={{
          position: "absolute",
          left: 58,
          top: 10,
          width: 179,
          height: 17,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 600,
          fontSize: 14,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(31,41,55)",
        }}>Restricciones alimentarias</span>
        <span style={{
          position: "absolute",
          left: 58,
          top: 28,
          width: 114,
          height: 13,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 11,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(107,114,128)",
        }}>Sin gluten, sin lactosa</span>
        <span style={{
          position: "absolute",
          left: 320,
          top: 19,
          width: 15,
          height: 14,
          fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 12,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(217,222,227)",
        }}>􀈗</span>
        <div style={{
          position: "absolute",
          left: 52,
          top: 52,
          width: 279,
          height: 1,
          backgroundColor: "rgb(242,244,245)",
        }} />
        <div style={{
          position: "absolute",
          left: 12,
          top: 60,
          width: 36,
          height: 36,
          overflow: "hidden",
          borderRadius: 10,
          backgroundColor: "rgba(237,237,255,0)",
        }}>
          <span style={{
            position: "absolute",
            left: 9,
            top: 8,
            width: 19,
            height: 20,
            fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
            fontWeight: 400,
            fontSize: 17,
            whiteSpace: "nowrap",
            lineHeight: "100%",
            color: "rgb(3,29,68)",
          }}>􀉇</span>
        </div>
        <span style={{
          position: "absolute",
          left: 58,
          top: 62,
          width: 46,
          height: 17,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 600,
          fontSize: 14,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(31,41,55)",
        }}>Idioma</span>
        <span style={{
          position: "absolute",
          left: 58,
          top: 80,
          width: 41,
          height: 13,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 11,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(107,114,128)",
        }}>Español</span>
        <span style={{
          position: "absolute",
          left: 320,
          top: 71,
          width: 15,
          height: 14,
          fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 12,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(217,222,227)",
        }}>􀈗</span>
        <div style={{
          position: "absolute",
          left: 52,
          top: 104,
          width: 279,
          height: 1,
          backgroundColor: "rgb(242,244,245)",
        }} />
        <div style={{
          position: "absolute",
          left: 12,
          top: 112,
          width: 36,
          height: 36,
          overflow: "hidden",
          borderRadius: 10,
          backgroundColor: "rgba(245,242,224,0)",
        }}>
          <span style={{
            position: "absolute",
            left: 9,
            top: 8,
            width: 20,
            height: 20,
            fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
            fontWeight: 400,
            fontSize: 17,
            whiteSpace: "nowrap",
            lineHeight: "100%",
            color: "rgb(3,29,68)",
          }}>􀉜</span>
        </div>
        <span style={{
          position: "absolute",
          left: 58,
          top: 123,
          width: 89,
          height: 17,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 600,
          fontSize: 14,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(31,41,55)",
        }}>Modo oscuro</span>
        <div style={{
          position: "absolute",
          left: 295,
          top: 117,
          width: 44,
          height: 26,
          overflow: "hidden",
          borderRadius: 13,
          backgroundColor: "rgb(217,222,227)",
        }}>
          <div style={{
            position: "absolute",
            left: 3,
            top: 3,
            width: 20,
            height: 20,
            borderRadius: 10,
            backgroundColor: "rgb(255,255,255)",
          }} />
        </div>
      </div>
      <span style={{
        position: "absolute",
        left: 20,
        top: 1274,
        width: 73,
        height: 12,
        fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
        fontWeight: 700,
        fontSize: 10,
        whiteSpace: "nowrap",
        lineHeight: "100%",
        letterSpacing: "1.200px",
        color: "rgb(107,114,128)",
      }}>PRIVACIDAD</span>
      <div style={{
        position: "absolute",
        left: 16,
        top: 1296,
        width: 343,
        height: 156,
        overflow: "hidden",
        borderRadius: 18,
        backgroundColor: "rgb(255,255,255)",
        boxShadow: "inset 0 0 0 1px rgb(217,222,227)",
      }}>
        <div style={{
          position: "absolute",
          left: 12,
          top: 8,
          width: 36,
          height: 36,
          overflow: "hidden",
          borderRadius: 10,
          backgroundColor: "rgba(245,237,255,0)",
        }}>
          <span style={{
            position: "absolute",
            left: 9,
            top: 8,
            width: 20,
            height: 20,
            fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
            fontWeight: 400,
            fontSize: 17,
            whiteSpace: "nowrap",
            lineHeight: "100%",
            color: "rgb(3,29,68)",
          }}>􀉰</span>
        </div>
        <span style={{
          position: "absolute",
          left: 58,
          top: 10,
          width: 153,
          height: 17,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 600,
          fontSize: 14,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(31,41,55)",
        }}>Permisos de ubicación</span>
        <span style={{
          position: "absolute",
          left: 58,
          top: 28,
          width: 77,
          height: 13,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 11,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(107,114,128)",
        }}>Siempre activa</span>
        <span style={{
          position: "absolute",
          left: 320,
          top: 19,
          width: 15,
          height: 14,
          fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 12,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(217,222,227)",
        }}>􀈗</span>
        <div style={{
          position: "absolute",
          left: 52,
          top: 52,
          width: 279,
          height: 1,
          backgroundColor: "rgb(242,244,245)",
        }} />
        <div style={{
          position: "absolute",
          left: 12,
          top: 60,
          width: 36,
          height: 36,
          overflow: "hidden",
          borderRadius: 10,
          backgroundColor: "rgba(224,247,232,0)",
        }}>
          <span style={{
            position: "absolute",
            left: 9,
            top: 8,
            width: 24,
            height: 20,
            fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
            fontWeight: 400,
            fontSize: 17,
            whiteSpace: "nowrap",
            lineHeight: "100%",
            color: "rgb(3,29,68)",
          }}>􀈞</span>
        </div>
        <span style={{
          position: "absolute",
          left: 58,
          top: 62,
          width: 66,
          height: 17,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 600,
          fontSize: 14,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(31,41,55)",
        }}>Mis datos</span>
        <span style={{
          position: "absolute",
          left: 58,
          top: 80,
          width: 151,
          height: 13,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 11,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(107,114,128)",
        }}>Descargar o eliminar historial</span>
        <span style={{
          position: "absolute",
          left: 320,
          top: 71,
          width: 15,
          height: 14,
          fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 12,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(217,222,227)",
        }}>􀈗</span>
        <div style={{
          position: "absolute",
          left: 52,
          top: 104,
          width: 279,
          height: 1,
          backgroundColor: "rgb(242,244,245)",
        }} />
        <div style={{
          position: "absolute",
          left: 12,
          top: 112,
          width: 36,
          height: 36,
          overflow: "hidden",
          borderRadius: 10,
          backgroundColor: "rgba(237,237,255,0)",
        }}>
          <span style={{
            position: "absolute",
            left: 9,
            top: 8,
            width: 21,
            height: 20,
            fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
            fontWeight: 400,
            fontSize: 17,
            whiteSpace: "nowrap",
            lineHeight: "100%",
            color: "rgb(3,29,68)",
          }}>􀈠</span>
        </div>
        <span style={{
          position: "absolute",
          left: 58,
          top: 123,
          width: 146,
          height: 17,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 600,
          fontSize: 14,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(31,41,55)",
        }}>Política de privacidad</span>
        <span style={{
          position: "absolute",
          left: 320,
          top: 123,
          width: 15,
          height: 14,
          fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 12,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(217,222,227)",
        }}>􀈗</span>
      </div>
      <span style={{
        position: "absolute",
        left: 20,
        top: 1470,
        width: 56,
        height: 12,
        fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
        fontWeight: 700,
        fontSize: 10,
        whiteSpace: "nowrap",
        lineHeight: "100%",
        letterSpacing: "1.200px",
        color: "rgb(107,114,128)",
      }}>SOPORTE</span>
      <div style={{
        position: "absolute",
        left: 16,
        top: 1492,
        width: 343,
        height: 156,
        overflow: "hidden",
        borderRadius: 18,
        backgroundColor: "rgb(255,255,255)",
        boxShadow: "inset 0 0 0 1px rgb(217,222,227)",
      }}>
        <div style={{
          position: "absolute",
          left: 12,
          top: 8,
          width: 36,
          height: 36,
          overflow: "hidden",
          borderRadius: 10,
          backgroundColor: "rgba(255,247,237,0)",
        }}>
          <span style={{
            position: "absolute",
            left: 9,
            top: 8,
            width: 20,
            height: 20,
            fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
            fontWeight: 400,
            fontSize: 17,
            whiteSpace: "nowrap",
            lineHeight: "100%",
            color: "rgb(3,29,68)",
          }}>􀉮</span>
        </div>
        <span style={{
          position: "absolute",
          left: 58,
          top: 19,
          width: 204,
          height: 17,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 600,
          fontSize: 14,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(31,41,55)",
        }}>Ayuda y preguntas frecuentes</span>
        <span style={{
          position: "absolute",
          left: 320,
          top: 19,
          width: 15,
          height: 14,
          fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 12,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(217,222,227)",
        }}>􀈗</span>
        <div style={{
          position: "absolute",
          left: 52,
          top: 52,
          width: 279,
          height: 1,
          backgroundColor: "rgb(242,244,245)",
        }} />
        <div style={{
          position: "absolute",
          left: 12,
          top: 60,
          width: 36,
          height: 36,
          overflow: "hidden",
          borderRadius: 10,
          backgroundColor: "rgba(224,247,232,0)",
        }}>
          <span style={{
            position: "absolute",
            left: 9,
            top: 8,
            width: 24,
            height: 20,
            fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
            fontWeight: 400,
            fontSize: 17,
            whiteSpace: "nowrap",
            lineHeight: "100%",
            color: "rgb(3,29,68)",
          }}>􀈲</span>
        </div>
        <span style={{
          position: "absolute",
          left: 58,
          top: 62,
          width: 153,
          height: 17,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 600,
          fontSize: 14,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(31,41,55)",
        }}>Contactar con soporte</span>
        <span style={{
          position: "absolute",
          left: 58,
          top: 80,
          width: 141,
          height: 13,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 11,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(107,114,128)",
        }}>Respuesta en menos de 2h</span>
        <span style={{
          position: "absolute",
          left: 320,
          top: 71,
          width: 15,
          height: 14,
          fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 12,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(217,222,227)",
        }}>􀈗</span>
        <div style={{
          position: "absolute",
          left: 52,
          top: 104,
          width: 279,
          height: 1,
          backgroundColor: "rgb(242,244,245)",
        }} />
        <div style={{
          position: "absolute",
          left: 12,
          top: 112,
          width: 36,
          height: 36,
          overflow: "hidden",
          borderRadius: 10,
          backgroundColor: "rgba(255,247,224,0)",
        }}>
          <span style={{
            position: "absolute",
            left: 9,
            top: 8,
            width: 26,
            height: 20,
            fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
            fontWeight: 400,
            fontSize: 17,
            whiteSpace: "nowrap",
            lineHeight: "100%",
            color: "rgb(3,29,68)",
          }}>􀉈</span>
        </div>
        <span style={{
          position: "absolute",
          left: 58,
          top: 123,
          width: 93,
          height: 17,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 600,
          fontSize: 14,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(31,41,55)",
        }}>Valorar Sabor</span>
        <span style={{
          position: "absolute",
          left: 320,
          top: 123,
          width: 15,
          height: 14,
          fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 12,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(217,222,227)",
        }}>􀈗</span>
      </div>
      <span style={{
        position: "absolute",
        left: 20,
        top: 1666,
        width: 44,
        height: 12,
        fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
        fontWeight: 700,
        fontSize: 10,
        whiteSpace: "nowrap",
        lineHeight: "100%",
        letterSpacing: "1.200px",
        color: "rgb(107,114,128)",
      }}>SESIÓN</span>
      <div style={{
        position: "absolute",
        left: 16,
        top: 1688,
        width: 343,
        height: 104,
        overflow: "hidden",
        borderRadius: 18,
        backgroundColor: "rgb(255,255,255)",
        boxShadow: "inset 0 0 0 1px rgb(217,222,227)",
      }}>
        <div style={{
          position: "absolute",
          left: 12,
          top: 8,
          width: 36,
          height: 36,
          overflow: "hidden",
          borderRadius: 10,
          backgroundColor: "rgb(255,240,240)",
        }}>
          <span style={{
            position: "absolute",
            left: 9,
            top: 8,
            width: 24,
            height: 20,
            fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
            fontWeight: 400,
            fontSize: 17,
            whiteSpace: "nowrap",
            lineHeight: "100%",
            color: "rgb(216,0,50)",
          }}>􀏆</span>
        </div>
        <span style={{
          position: "absolute",
          left: 58,
          top: 19,
          width: 92,
          height: 17,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 600,
          fontSize: 14,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(216,0,50)",
        }}>Cerrar sesión</span>
        <span style={{
          position: "absolute",
          left: 320,
          top: 19,
          width: 15,
          height: 14,
          fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 12,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(217,222,227)",
        }}>􀈗</span>
        <div style={{
          position: "absolute",
          left: 52,
          top: 52,
          width: 279,
          height: 1,
          backgroundColor: "rgb(242,244,245)",
        }} />
        <div style={{
          position: "absolute",
          left: 12,
          top: 60,
          width: 36,
          height: 36,
          overflow: "hidden",
          borderRadius: 10,
          backgroundColor: "rgb(255,240,240)",
        }}>
          <span style={{
            position: "absolute",
            left: 9,
            top: 8,
            width: 24,
            height: 20,
            fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
            fontWeight: 400,
            fontSize: 17,
            whiteSpace: "nowrap",
            lineHeight: "100%",
            color: "rgb(216,0,50)",
          }}>􀈜</span>
        </div>
        <span style={{
          position: "absolute",
          left: 58,
          top: 62,
          width: 105,
          height: 17,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 600,
          fontSize: 14,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(216,0,50)",
        }}>Eliminar cuenta</span>
        <span style={{
          position: "absolute",
          left: 58,
          top: 80,
          width: 179,
          height: 13,
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 11,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(107,114,128)",
        }}>Esta acción no se puede deshacer</span>
        <span style={{
          position: "absolute",
          left: 320,
          top: 71,
          width: 15,
          height: 14,
          fontFamily: "\"SF Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 400,
          fontSize: 12,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(217,222,227)",
        }}>􀈗</span>
      </div>
      <div style={{
        position: "absolute",
        left: 0,
        top: 0,
        transform: "matrix(1,0,0,-1,-6,80)",
        transformOrigin: "0 0",
        width: 402,
        height: 80,
        background: "linear-gradient(180deg, rgba(255,227,157,0) -0.00%, rgba(255,255,255,0.0315) 100.00%)",
        backdropFilter: "blur(30px)",
      }} />
      <div style={{
        position: "absolute",
        left: -5,
        top: 738,
        width: 390,
        height: 118,
        background: "linear-gradient(180deg, rgba(255,227,157,0) -0.00%, rgba(255,255,255,0.018) 100.00%)",
        backdropFilter: "blur(30px)",
      }} />
      <div style={{
        position: "absolute",
        left: 15,
        top: 761.775,
        width: 351,
        height: 69.841,
        overflow: "hidden",
      }}>
        <div style={{
          position: "absolute",
          left: 0,
          top: 9.36,
          width: 351,
          height: 60.481,
          overflow: "hidden",
        }}>
          <svg width={351} height={60.481} viewBox="0 0 351 60.481" fill="none" style={{
            position: "absolute",
            left: 0,
            top: 0,
            width: 351,
            height: 60.481,
            borderRadius: 25,
          }}>
            <path d={"M 244.762 0 C 258.134 0 268.702 11.984 278.39 21.201 C 284.087 26.62 291.805 29.952 300.241 29.952 C 304.903 29.952 309.345 28.935 313.348 27.11 C 328.276 20.305 348.674 10.095 350.754 26.368 C 350.916 27.636 351 28.928 351 30.24 C 351 46.942 337.461 60.481 320.76 60.481 L 30.24 60.481 C 13.539 60.481 0 46.942 0 30.24 C 0 13.539 13.539 0 30.24 0 L 244.762 0 Z"} fill="currentColor" fillRule="nonzero" />
          </svg>
        </div>
        <span style={{
          position: "absolute",
          left: 156.312,
          top: 26.208,
          width: 35.568,
          height: 25.272,
          fontFamily: "\"SF Pro Display\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 500,
          fontSize: 30,
          textAlign: "center",
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(255,255,255)",
        }}>􀎞</span>
        <span style={{
          position: "absolute",
          left: 288.288,
          top: 0,
          width: 29.016,
          height: 28.08,
          fontFamily: "\"SF Pro Display\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 500,
          fontSize: 25,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(3,29,68)",
        }}>􀉩</span>
        <span style={{
          position: "absolute",
          left: 94.536,
          top: 25.272,
          width: 33.696,
          height: 28.08,
          fontFamily: "\"SF Pro Display\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 500,
          fontSize: 25,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(255,255,255)",
        }}>􀙊</span>
        <span style={{
          position: "absolute",
          left: 229.32,
          top: 26.208,
          width: 26.208,
          height: 28.08,
          fontFamily: "\"SF Pro Display\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 500,
          fontSize: 25,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(255,255,255)",
        }}>􀉞</span>
        <span style={{
          position: "absolute",
          left: 17.784,
          top: 25.272,
          width: 48.672,
          height: 28.08,
          fontFamily: "\"SF Pro Display\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 500,
          fontSize: 25,
          whiteSpace: "nowrap",
          lineHeight: "100%",
          color: "rgb(255,255,255)",
        }}>􀝊</span>
      </div>
    </div>
  );
}
export default AjustesIPhone14;
